### ISSUE TITLE
Errors in \Affirm\Telesales\Controller\Payment\Success::execute and \Affirm\Telesales\Controller\Payment\Cancel::execute

### ISSUE THREAD

**Issue by pkarsai** [Affirm/Magento2_Affirm_Telesales#20]
Both methods contain the following code:
```        
        $messages = $this->messageManager->getMessages();
        if ($messages) {
            $this->messageManager->addErrorMessage($messages);
        }
```
The problem with this is `$messages` is of type `\Magento\Framework\Message\Collection`, while the called method – `\Magento\Framework\Message\ManagerInterface::addErrorMessage` – expects a single `string`.

This results in the following error to the customer when they finish completing their loan application:

```
Error: Object of class Magento Framework\ Message\Collection could not be converted to string in /var /www/magento/vendor/magento/framework/Message/AbstractMessage.php:59
Stack trace:
#0 /var/www/magento/vendor/magento/framework/View/Element/Message/Renderer/EscapeRenderer.php(41):Magento\Framework\Message\AbstractMessage->getText()
#1
/var /www/magento/vendor/magento/framework/View/Element/Message/InterpretationStrategy-php(56):Magento\Framework\View\Element\Message\Renderer\EscapeRenderer->render()
#2 /var/www/magento/vendor/magento/framework/View/Element/Message/InterpretationMediator.php(41):Magento\Framework\View\Element\Message\InterpretationStrategy->interpret()
#3 /var /www/magento/vendor/magento/module-theme/Controller/Result/MessagePlugin.php(108):Magento\Framework\View\Element\Message\InterpretationMediator->interpret()
#4 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(146):Magento\Theme\Controller\Result\MessagePlugin-afterRenderResult()
#5 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\ Framework\View\Result\Page\ Interceptor->Magento \Framework\ Interception\ (closure] ( )
#6 /var/www/magento/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor-> callPlugins ( )
#7 /var/www/magento/vendor/magento/framework/App/Bittp-php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult ()
#8 /var/www/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework \App\Ettp-> launch ()
#9 /var /www/magento/vendor/magento/framework/App/Bootstrap.php (264): Magento\Framework\App\Http\Interceptor->launch ( )
#10
/var/www/magento/pub/index.php (30): Magento\Framework \App\Bootstrap-›run()
#11 (main)
```

On an unrelated note, `telesales_payment_cancel.xml` is missing its `<body></body>` tags.

**Comment by taehyunlim** [comment]
Hi @pkarsai - thank you for bringing this to our attention. We will look into resolving the issue with the incorrect argument type.
